import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Fira_Code } from 'next/font/google'
import NextTopLoader from 'nextjs-toploader'


const fira_code = Fira_Code({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={fira_code.className}>

        <NextTopLoader
          color="#2299DD"
          initialPosition={0.08}
          crawlSpeed={200}
          height={7}
          crawl={true}
          showSpinner={true}
          easing="ease"
          speed={200}
          shadow="0 0 10px sky-blue,0 0 5px #2299DD" />
        <Navbar />
        <main>
          {children}
        </main>

      </body>
    </html>
  )
}


